services:
  - type: web
    name: employeehub
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python seed.py && gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: employeehub-db
          property: connectionString
      - key: USE_SQLITE
        value: "false"

databases:
  - name: employeehub-db
    plan: free
    databaseName: employeehub_db
    user: employeehub_user
